-- Story Content Centralization
-- Move all story content to Supabase as single source of truth

-- ───────────────────────────────────────────────────────────────────────────────
-- STORIES TABLE: Authoritative story content
-- ───────────────────────────────────────────────────────────────────────────────
create table if not exists stories (
  id bigint primary key generated by default as identity,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),

  -- Story content (JSONB)
  prologue jsonb not null default '{"lines": [], "signoff": ""}',
  days jsonb not null default '[]',
  flow_map jsonb not null default '{"rules": []}',

  -- Publishing state
  is_published boolean default false,
  published_at timestamptz,

  -- Metadata
  author_id uuid,
  version_number int default 1,
  change_notes text,

  -- Constraints
  constraint valid_version check (version_number > 0)
);

-- Enable RLS
alter table stories enable row level security;

-- Policy: anon can read published stories only
create policy "anon can read published stories"
  on stories for select
  to anon
  using (is_published = true);

-- Policy: admin (authenticated) can read all and write drafts
-- Note: Implement admin auth check in application
create policy "authenticated can read all"
  on stories for select
  to authenticated
  using (true);

create policy "authenticated can create"
  on stories for insert
  to authenticated
  with check (true);

create policy "authenticated can update"
  on stories for update
  to authenticated
  using (true)
  with check (true);

-- ───────────────────────────────────────────────────────────────────────────────
-- STORY_VERSIONS TABLE: Version history and audit trail
-- ───────────────────────────────────────────────────────────────────────────────
create table if not exists story_versions (
  id bigint primary key generated by default as identity,
  story_id bigint references stories(id) on delete cascade not null,
  created_at timestamptz default now(),

  -- Content snapshot
  prologue jsonb not null,
  days jsonb not null,
  flow_map jsonb not null,

  -- Metadata
  author_id uuid,
  version_number int not null,
  change_notes text,
  is_published_version boolean default false,
  published_at timestamptz
);

-- Enable RLS
alter table story_versions enable row level security;

-- Policy: anon can read versions of published stories
create policy "anon can read published story versions"
  on story_versions for select
  to anon
  using (
    exists (
      select 1 from stories s
      where s.id = story_id and s.is_published = true
    )
  );

-- Policy: authenticated can read all versions
create policy "authenticated can read all versions"
  on story_versions for select
  to authenticated
  using (true);

-- Policy: only service role can insert (controlled by admin)
create policy "service role can insert versions"
  on story_versions for insert
  with check (true);

-- ───────────────────────────────────────────────────────────────────────────────
-- PLAYER_STATE TABLE: Player progress and game state
-- ───────────────────────────────────────────────────────────────────────────────
create table if not exists player_state (
  id text primary key,
  state jsonb not null default '{}',
  story_version_id bigint references story_versions(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable RLS
alter table player_state enable row level security;

-- Policy: player can upsert their own state
create policy "anon can read/write player state"
  on player_state for all
  to anon
  using (true)
  with check (true);

-- ───────────────────────────────────────────────────────────────────────────────
-- PLAYER_RESPONSES TABLE: Player's responses to choices
-- ───────────────────────────────────────────────────────────────────────────────
create table if not exists player_responses (
  id bigint primary key generated by default as identity,
  envelope_id text not null,
  choice_id text not null,
  story_version_id bigint references story_versions(id),
  responses jsonb not null default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),

  -- Composite unique: only one response per choice per version
  constraint one_response_per_choice unique (envelope_id, choice_id, story_version_id)
);

-- Enable RLS
alter table player_responses enable row level security;

-- Policy: player can insert/update their own responses
create policy "anon can insert/update responses"
  on player_responses for all
  to anon
  using (true)
  with check (true);

-- ───────────────────────────────────────────────────────────────────────────────
-- INDEXES
-- ───────────────────────────────────────────────────────────────────────────────

-- Speed up published story lookups
create index if not exists idx_stories_published on stories(is_published, published_at desc);

-- Speed up version lookups by story
create index if not exists idx_story_versions_by_story on story_versions(story_id, version_number desc);

-- Speed up player response lookups
create index if not exists idx_player_responses_envelope_choice on player_responses(envelope_id, choice_id);

-- ───────────────────────────────────────────────────────────────────────────────
-- INITIAL DATA
-- ───────────────────────────────────────────────────────────────────────────────

-- Insert placeholder published story (will be replaced by admin export)
-- Start with empty story so player doesn't crash
insert into stories (prologue, days, flow_map, is_published, published_at, version_number, change_notes)
values (
  '{"lines": ["Loading story..."], "signoff": "..."}',
  '[]',
  '{"rules": []}',
  true,
  now(),
  1,
  'Initial placeholder'
) on conflict do nothing;
